source 'http://rubygems.org'

gem 'jekyll'
gem 'jekyll-asset-pipeline', :git => 'https://github.com/matthodan/jekyll-asset-pipeline.git'
gem 'jekyll-redirect-from'
gem 'slim'
gem 'jekyll-slim'
gem 'sass'
gem 'coffee-script'
gem 'yui-compressor'
gem 'rubytree'
gem 'activesupport', :require => 'active_support/all'
gem 'elastics-client', :path => '../../elastics/elastics'
