source 'http://rubygems.org'

gem 'jekyll'
gem 'jekyll-asset-pipeline', :git => 'https://github.com/matthodan/jekyll-asset-pipeline.git'
gem 'slim', '~>2.0.0'
gem 'jekyll-slim', '~> 0.8.2'
gem 'sass'
gem 'coffee-script'
gem 'yui-compressor'
gem 'rubytree'
gem 'activesupport', :require => 'active_support/all'
